services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: ["npm", "start"]