name: 🚀 Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Connect via SSH & Run Deploy Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Menjalankan deploy script di server..."
            bash /home/ubuntu/deploykasma.sh
